In [1]:
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import nltk
from nltk.corpus import stopwords
nltk.download('punkt')
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.metrics import accuracy_score
from tqdm.notebook import tqdm
tqdm.pandas(desc="progress-bar")
import gensim
import gensim.downloader as api
from gensim import models
from gensim.models import Doc2Vec
from gensim.test.test_doc2vec import ConcatenatedDoc2Vec
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from gensim.models.doc2vec import TaggedDocument
from sklearn.utils import shuffle

import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sanke\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
df = pd.read_excel('Code Mixed Hindi-English tweets.xlsx')
df.drop(['id'],axis=1, inplace=True)
df

tweets  labels
0     aaj ka khel khatam hone k baad england cricket...       0
1                            purana manjan bech rha hai       5
2                  tumhare disappointed se kuch ni hoga       0
3     inse bas tiktok banva lo batting ni hoti isse ...       3
4     bhai cricket par tweets mat kara karo please j...       3
...                                                 ...     ...
9160              gujarati fraud kyu hotey hai? pnbscam       3
9161  saala idhar 7 lakh k car loan k liye bank choo...       3
9162  mitron nirav modi ji ka relation india k kaun ...       3
9163  or yahn ek month k education loan ki emi pay n...       2
9164  jis bank me 500 rupye niklwane k liye ghnto kh...       3

[9165 rows x 2 columns]

# Labels are as follows:
0 - No emotions,
1 - Happy,
2 - Sad,
3 - Angry,
4 - Fear,
5 - Disgust,
6 - Surprise

In [3]:
print("Dataset shape: ", df.shape)
df['labels'].value_counts()

Dataset shape:  (9165, 2)


0    1892
3    1763
2    1529
1    1226
5    1147
6    1049
4     559
Name: labels, dtype: int64

# 1. Models without Removing anything:

### Splitting data into Train and Test &&& Tokenizing tweets

In [4]:
train, test = train_test_split(df, test_size=0.2, random_state=3)

# Creating a function for tokens
def tokenize_text(text):
    tokens = []
    for sent in nltk.sent_tokenize(text):
        for word in nltk.word_tokenize(sent):
            if len(word) < 2:
                continue
            tokens.append(word.lower())
    return tokens

# Tagging words:
train_tagged = train.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)
test_tagged = test.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)

train_tagged.values[0]

TaggedDocument(words=['modi', 'ne', 'to', 'ensure', 'kr', 'diya', 'demonetization', 'aur', 'gst', 'unthinkable', 'rates', 'se', 'ki', 'garib', 'marr', 'hi', 'jai', 'ni', 'rha', 'garib', 'aur', 'ni', 'rahegi', 'garibi'], tags=[2])

# Doc2vec:
### Distributed Memory (DM)
Note: If dm=0, distributed bag of words (PV-DBOW) is used; if dm=1,‘distributed memory’ (PV-DM) is used.

### Building DM model:

In [5]:
import multiprocessing
cores = multiprocessing.cpu_count()

model_dmm = Doc2Vec(dm=1, dm_mean=1, vector_size=300, window=10, negative=5, min_count=1, workers=5, alpha=0.065, min_alpha=0.065)
model_dmm.build_vocab([x for x in tqdm(train_tagged.values)])

for epoch in range(30):
    model_dmm.train(shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dmm.alpha -= 0.002
    model_dmm.min_alpha = model_dmm.alpha

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

### Creating Final feature vector:

In [6]:
# Building the Final Feature Vector for the Classifier
def vec_for_learning(model, tagged_docs):
    sents = tagged_docs.values
    targets, regressors = zip(*[(doc.tags[0], model.infer_vector(doc.words)) for doc in sents])
    return targets, regressors

# Creating X_train, X_test, y_train, y_test
y_train, X_train = vec_for_learning(model_dmm, train_tagged)
y_test, X_test = vec_for_learning(model_dmm, test_tagged)

### Base Models:

In [7]:
# making a dictionary with four models with some parameters:
model_params = {
    
    'SVC' :{
        'model' : SVC(),
        'params' : {
            'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01], 'kernel': ['rbf','linear','poly','sigmoid']
        }
    },
    
    'logistics_regression' :{
        'model' : LogisticRegression(solver = 'lbfgs', multi_class = 'auto'),
        'params' : {
            'C' : [0.1, 1, 20, 40, 60, 80, 100], 'solver' : ['lbfgs', 'liblinear']
        }
    },
    
    'random_forest' :{
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [80,85,90,95,100], 
            'max_depth':[20,30,None], 'criterion':['gini','entropy']
        }
    }
}

### Results:

In [8]:
%%time

# implemented GridSearchCV for four models using a loop and a previously created dictionary
# in the created variable 'scores', results are stored for each model such as: model, best_score and best_params.

scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, n_jobs=-1, verbose=1) # Using Cross Validation of 5 and n_jobs=-1 for fast training by using all the processors
    print(mp['model'])
    print('\nFitting...')
    best_model = clf.fit(X_train, y_train)                      # Training the model
    clf_pred = best_model.predict(X_test)                       # Predicting the results
    print(confusion_matrix(y_test,clf_pred))                    # Printing Confusion Matrix
    print(metrics.classification_report(y_test, clf_pred))      # Printing Classification Report
    scores.append({                                             # Appending results to 'scores' list
        'model' : model_name,
        'best_score' : best_model.score(X_test, y_test),
        'best_params' : clf.best_params_
    })
    print('\nScore is appended.\n')
    
# Creating data frame with model, best scores and best params:
res = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
res

SVC()

Fitting...
Fitting 5 folds for each of 48 candidates, totalling 240 fits
[[219  34  21  15  13   5  54]
 [ 77  96   8   7  12   2  40]
 [109  57  48  15  19   5  57]
 [142  56  16  34  20  10  68]
 [ 43  16   4   8  21   0  12]
 [ 72  27  13  13  16  62  36]
 [ 71  25   9   5   8   3 110]]
              precision    recall  f1-score   support

           0       0.30      0.61      0.40       361
           1       0.31      0.40      0.35       242
           2       0.40      0.15      0.22       310
           3       0.35      0.10      0.15       346
           4       0.19      0.20      0.20       104
           5       0.71      0.26      0.38       239
           6       0.29      0.48      0.36       231

    accuracy                           0.32      1833
   macro avg       0.37      0.31      0.29      1833
weighted avg       0.37      0.32      0.30      1833


Score is appended.

LogisticRegression()

Fitting...
Fitting 5 folds for each of 14 candidates, totallin

model  best_score  \
0                   SVC    0.321877   
1  logistics_regression    0.326787   
2         random_forest    0.240589   

                                         best_params  
0            {'C': 100, 'gamma': 1, 'kernel': 'rbf'}  
1                  {'C': 100, 'solver': 'liblinear'}  
2  {'criterion': 'gini', 'max_depth': 30, 'n_esti...

# 2. Models after removing Stopwords:

In [9]:
df = pd.read_excel('Code Mixed Hindi-English tweets.xlsx')

### Removing Stopwords:

In [10]:
# Using Hinglish stopwords which contains 1036 words from both English and Hindi languages
# Source: https://github.com/TrigonaMinima/HinglishNLP/blob/master/data/assets/stop_hinglish

stopwordlist = ['a', 'aadi', 'aaj', 'aap', 'aapne', 'aata', 'aati', 'aaya', 'aaye', 'ab', 'abbe', 'abbey', 'abe', 'abhi', 'able', 'about', 'above', 'accha', 'according', 'accordingly', 'acha', 'achcha', 'across', 'actually', 'after', 'afterwards', 'again', 'against', 'agar', 'ain', 'aint', "ain't", 'aisa', 'aise', 'aisi', 'alag', 'all', 'allow', 'allows', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'an', 'and', 'andar', 'another', 'any', 'anybody', 'anyhow', 'anyone', 'anything', 'anyway', 'anyways', 'anywhere', 'ap', 'apan', 'apart', 'apna', 'apnaa', 'apne', 'apni', 'appear', 'are', 'aren', 'arent', "aren't", 'around', 'arre', 'as', 'aside', 'ask', 'asking', 'at', 'aur', 'avum', 'aya', 'aye', 'baad', 'baar', 'bad', 'bahut', 'bana', 'banae', 'banai', 'banao', 'banaya', 'banaye', 'banayi', 'banda', 'bande', 'bandi', 'bane', 'bani', 'bas', 'bata', 'batao', 'bc', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'best', 'better', 'between', 'beyond', 'bhai', 'bheetar', 'bhi', 'bhitar', 'bht', 'bilkul', 'bohot', 'bol', 'bola', 'bole', 'boli', 'bolo', 'bolta', 'bolte', 'bolti', 'both', 'brief', 'bro', 'btw', 'but', 'by', 'came', 'can', 'cannot', 'cant', "can't", 'cause', 'causes', 'certain', 'certainly', 'chahiye', 'chaiye', 'chal', 'chalega', 'chhaiye', 'clearly', "c'mon", 'com', 'come', 'comes', 'could', 'couldn', 'couldnt', "couldn't", 'd', 'de', 'dede', 'dega', 'degi', 'dekh', 'dekha', 'dekhe', 'dekhi', 'dekho', 'denge', 'dhang', 'di', 'did', 'didn', 'didnt', "didn't", 'dijiye', 'diya', 'diyaa', 'diye', 'diyo', 'do', 'does', 'doesn', 'doesnt', "doesn't", 'doing', 'done', 'dono', 'dont', "don't", 'doosra', 'doosre', 'down', 'downwards', 'dude', 'dunga', 'dungi', 'during', 'dusra', 'dusre', 'dusri', 'dvaara', 'dvara', 'dwaara', 'dwara', 'each', 'edu', 'eg', 'eight', 'either', 'ek', 'else', 'elsewhere', 'enough', 'etc', 'even', 'ever', 'every', 'everybody', 'everyone', 'everything', 'everywhere', 'ex', 'exactly', 'example', 'except', 'far', 'few', 'fifth', 'fir', 'first', 'five', 'followed', 'following', 'follows', 'for', 'forth', 'four', 'from', 'further', 'furthermore', 'gaya', 'gaye', 'gayi', 'get', 'gets', 'getting', 'ghar', 'given', 'gives', 'go', 'goes', 'going', 'gone', 'good', 'got', 'gotten', 'greetings', 'haan', 'had', 'hadd', 'hadn', 'hadnt', "hadn't", 'hai', 'hain', 'hamara', 'hamare', 'hamari', 'hamne', 'han', 'happens', 'har', 'hardly', 'has', 'hasn', 'hasnt', "hasn't", 'have', 'haven', 'havent', "haven't", 'having', 'he', 'hello', 'help', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', "here's", 'hereupon', 'hers', 'herself', "he's", 'hi', 'him', 'himself', 'his', 'hither', 'hm', 'hmm', 'ho', 'hoga', 'hoge', 'hogi', 'hona', 'honaa', 'hone', 'honge', 'hongi', 'honi', 'hopefully', 'hota', 'hotaa', 'hote', 'hoti', 'how', 'howbeit', 'however', 'hoyenge', 'hoyengi', 'hu', 'hua', 'hue', 'huh', 'hui', 'hum', 'humein', 'humne', 'hun', 'huye', 'huyi', 'i', "i'd", 'idk', 'ie', 'if', "i'll", "i'm", 'imo', 'in', 'inasmuch', 'inc', 'inhe', 'inhi', 'inho', 'inka', 'inkaa', 'inke', 'inki', 'inn', 'inner', 'inse', 'insofar', 'into', 'inward', 'is', 'ise', 'isi', 'iska', 'iskaa', 'iske', 'iski', 'isme', 'isn', 'isne', 'isnt', "isn't", 'iss', 'isse', 'issi', 'isski', 'it', "it'd", "it'll", 'itna', 'itne', 'itni', 'itno', 'its', "it's", 'itself', 'ityaadi', 'ityadi', "i've", 'ja', 'jaa', 'jab', 'jabh', 'jaha', 'jahaan', 'jahan', 'jaisa', 'jaise', 'jaisi', 'jata', 'jayega', 'jidhar', 'jin', 'jinhe', 'jinhi', 'jinho', 'jinhone', 'jinka', 'jinke', 'jinki', 'jinn', 'jis', 'jise', 'jiska', 'jiske', 'jiski', 'jisme', 'jiss', 'jisse', 'jitna', 'jitne', 'jitni', 'jo', 'just', 'jyaada', 'jyada', 'k', 'ka', 'kaafi', 'kab', 'kabhi', 'kafi', 'kaha', 'kahaa', 'kahaan', 'kahan', 'kahi', 'kahin', 'kahte', 'kaisa', 'kaise', 'kaisi', 'kal', 'kam', 'kar', 'kara', 'kare', 'karega', 'karegi', 'karen', 'karenge', 'kari', 'karke', 'karna', 'karne', 'karni', 'karo', 'karta', 'karte', 'karti', 'karu', 'karun', 'karunga', 'karungi', 'kaun', 'kaunsa', 'kayi', 'kch', 'ke', 'keep', 'keeps', 'keh', 'kehte', 'kept', 'khud', 'ki', 'kin', 'kine', 'kinhe', 'kinho', 'kinka', 'kinke', 'kinki', 'kinko', 'kinn', 'kino', 'kis', 'kise', 'kisi', 'kiska', 'kiske', 'kiski', 'kisko', 'kisliye', 'kisne', 'kitna', 'kitne', 'kitni', 'kitno', 'kiya', 'kiye', 'know', 'known', 'knows', 'ko', 'koi', 'kon', 'konsa', 'koyi', 'krna', 'krne', 'kuch', 'kuchch', 'kuchh', 'kul', 'kull', 'kya', 'kyaa', 'kyu', 'kyuki', 'kyun', 'kyunki', 'lagta', 'lagte', 'lagti', 'last', 'lately', 'later', 'le', 'least', 'lekar', 'lekin', 'less', 'lest', 'let', "let's", 'li', 'like', 'liked', 'likely', 'little', 'liya', 'liye', 'll', 'lo', 'log', 'logon', 'lol', 'look', 'looking', 'looks', 'ltd', 'lunga', 'm', 'maan', 'maana', 'maane', 'maani', 'maano', 'magar', 'mai', 'main', 'maine', 'mainly', 'mana', 'mane', 'mani', 'mano', 'many', 'mat', 'may', 'maybe', 'me', 'mean', 'meanwhile', 'mein', 'mera', 'mere', 'merely', 'meri', 'might', 'mightn', 'mightnt', "mightn't", 'mil', 'mjhe', 'more', 'moreover', 'most', 'mostly', 'much', 'mujhe', 'must', 'mustn', 'mustnt', "mustn't", 'my', 'myself', 'na', 'naa', 'naah', 'nahi', 'nahin', 'nai', 'name', 'namely', 'nd', 'ne', 'near', 'nearly', 'necessary', 'neeche', 'need', 'needn', 'neednt', "needn't", 'needs', 'neither', 'never', 'nevertheless', 'new', 'next', 'nhi', 'nine', 'no', 'nobody', 'non', 'none', 'noone', 'nope', 'nor', 'normally', 'not', 'nothing', 'novel', 'now', 'nowhere', 'o', 'obviously', 'of', 'off', 'often', 'oh', 'ok', 'okay', 'old', 'on', 'once', 'one', 'ones', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'ought', 'our', 'ours', 'ourselves', 'out', 'outside', 'over', 'overall', 'own', 'par', 'pata', 'pe', 'pehla', 'pehle', 'pehli', 'people', 'per', 'perhaps', 'phla', 'phle', 'phli', 'placed', 'please', 'plus', 'poora', 'poori', 'provides', 'pura', 'puri', 'q', 'que', 'quite', 'raha', 'rahaa', 'rahe', 'rahi', 'rakh', 'rakha', 'rakhe', 'rakhen', 'rakhi', 'rakho', 'rather', 're', 'really', 'reasonably', 'regarding', 'regardless', 'regards', 'rehte', 'rha', 'rhaa', 'rhe', 'rhi', 'ri', 'right', 's', 'sa', 'saara', 'saare', 'saath', 'sab', 'sabhi', 'sabse', 'sahi', 'said', 'sakta', 'saktaa', 'sakte', 'sakti', 'same', 'sang', 'sara', 'sath', 'saw', 'say', 'saying', 'says', 'se', 'second', 'secondly', 'see', 'seeing', 'seem', 'seemed', 'seeming', 'seems', 'seen', 'self', 'selves', 'sensible', 'sent', 'serious', 'seriously', 'seven', 'several', 'shall', 'shan', 'shant', "shan't", 'she', "she's", 'should', 'shouldn', 'shouldnt', "shouldn't", "should've", 'si', 'since', 'six', 'so', 'soch', 'some', 'somebody', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhat', 'somewhere', 'soon', 'still', 'sub', 'such', 'sup', 'sure', 't', 'tab', 'tabh', 'tak', 'take', 'taken', 'tarah', 'teen', 'teeno', 'teesra', 'teesre', 'teesri', 'tell', 'tends', 'tera', 'tere', 'teri', 'th', 'tha', 'than', 'thank', 'thanks', 'thanx', 'that', "that'll", 'thats', "that's", 'the', 'theek', 'their', 'theirs', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'theres', "there's", 'thereupon', 'these', 'they', "they'd", "they'll", "they're", "they've", 'thi', 'thik', 'thing', 'think', 'thinking', 'third', 'this', 'tho', 'thoda', 'thodi', 'thorough', 'thoroughly', 'those', 'though', 'thought', 'three', 'through', 'throughout', 'thru', 'thus', 'tjhe', 'to', 'together', 'toh', 'too', 'took', 'toward', 'towards', 'tried', 'tries', 'true', 'truly', 'try', 'trying', 'tu', 'tujhe', 'tum', 'tumhara', 'tumhare', 'tumhari', 'tune', 'twice', 'two', 'um', 'umm', 'un', 'under', 'unhe', 'unhi', 'unho', 'unhone', 'unka', 'unkaa', 'unke', 'unki', 'unko', 'unless', 'unlikely', 'unn', 'unse', 'until', 'unto', 'up', 'upar', 'upon', 'us', 'use', 'used', 'useful', 'uses', 'usi', 'using', 'uska', 'uske', 'usne', 'uss', 'usse', 'ussi', 'usually', 'vaala', 'vaale', 'vaali', 'vahaan', 'vahan', 'vahi', 'vahin', 'vaisa', 'vaise', 'vaisi', 'vala', 'vale', 'vali', 'various', 've', 'very', 'via', 'viz', 'vo', 'waala', 'waale', 'waali', 'wagaira', 'wagairah', 'wagerah', 'waha', 'wahaan', 'wahan', 'wahi', 'wahin', 'waisa', 'waise', 'waisi', 'wala', 'wale', 'wali', 'want', 'wants', 'was', 'wasn', 'wasnt', "wasn't", 'way', 'we', "we'd", 'well', "we'll", 'went', 'were', "we're", 'weren', 'werent', "weren't", "we've", 'what', 'whatever', "what's", 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', "where's", 'whereupon', 'wherever', 'whether', 'which', 'while', 'who', 'whoever', 'whole', 'whom', "who's", 'whose', 'why', 'will', 'willing', 'with', 'within', 'without', 'wo', 'woh', 'wohi', 'won', 'wont', "won't", 'would', 'wouldn', 'wouldnt', "wouldn't", 'y', 'ya', 'yadi', 'yah', 'yaha', 'yahaan', 'yahan', 'yahi', 'yahin', 'ye', 'yeah', 'yeh', 'yehi', 'yes', 'yet', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've", 'yup']

STOPWORDS = set(stopwordlist)
def cleaning_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

df['tweets'] = df['tweets'].apply(lambda text: cleaning_stopwords(text))

### Splitting data into Train and Test &&& Tokenizing tweets

In [11]:
train, test = train_test_split(df, test_size=0.2, random_state=3)

# Creating a function for tokens
def tokenize_text(text):
    tokens = []
    for sent in nltk.sent_tokenize(text):
        for word in nltk.word_tokenize(sent):
            if len(word) < 2:
                continue
            tokens.append(word.lower())
    return tokens

# Tagging words:
train_tagged = train.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)
test_tagged = test.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)

train_tagged.values[0]

TaggedDocument(words=['modi', 'ensure', 'kr', 'demonetization', 'gst', 'unthinkable', 'rates', 'garib', 'marr', 'jai', 'ni', 'garib', 'ni', 'rahegi', 'garibi'], tags=[2])

# Doc2vec:
### Distributed Memory (DM)
Note: If dm=0, distributed bag of words (PV-DBOW) is used; if dm=1,‘distributed memory’ (PV-DM) is used.

### Building DM models:

In [12]:
import multiprocessing
cores = multiprocessing.cpu_count()

model_dmm = Doc2Vec(dm=1, dm_mean=1, vector_size=300, window=10, negative=5, min_count=1, workers=5, alpha=0.065, min_alpha=0.065)
model_dmm.build_vocab([x for x in tqdm(train_tagged.values)])

for epoch in range(30):
    model_dmm.train(shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dmm.alpha -= 0.002
    model_dmm.min_alpha = model_dmm.alpha

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

### Creating Final feature vector:

In [13]:
# Building the Final Feature Vector for the Classifier
def vec_for_learning(model, tagged_docs):
    sents = tagged_docs.values
    targets, regressors = zip(*[(doc.tags[0], model.infer_vector(doc.words)) for doc in sents])
    return targets, regressors

# Creating X_train, X_test, y_train, y_test
y_train, X_train = vec_for_learning(model_dmm, train_tagged)
y_test, X_test = vec_for_learning(model_dmm, test_tagged)

### Results:

In [14]:
%%time

# implemented GridSearchCV for four models using a loop and a previously created dictionary
# in the created variable 'scores', results are stored for each model such as: model, best_score and best_params.

scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, n_jobs=-1, verbose=1) # Using Cross Validation of 5 and n_jobs=-1 for fast training by using all the processors
    print(mp['model'])
    print('\nFitting...')
    best_model = clf.fit(X_train, y_train)                      # Training the model
    clf_pred = best_model.predict(X_test)                       # Predicting the results
    print(confusion_matrix(y_test,clf_pred))                    # Printing Confusion Matrix
    print(metrics.classification_report(y_test, clf_pred))      # Printing Classification Report
    scores.append({                                             # Appending results to 'scores' list
        'model' : model_name,
        'best_score' : best_model.score(X_test, y_test),
        'best_params' : clf.best_params_
    })
    print('\nScore is appended.\n')
    
# Creating data frame with model, best scores and best params:
res = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
res

SVC()

Fitting...
Fitting 5 folds for each of 48 candidates, totalling 240 fits
[[179  42  19  30  11  10  70]
 [ 68  93  17   7   8   5  44]
 [ 98  50  77  14  11   7  53]
 [ 76  57  31  65  15  11  91]
 [ 25   8   7  16  24   4  20]
 [ 52  36  19  22  14  55  41]
 [ 76  19  10  10  10   4 102]]
              precision    recall  f1-score   support

           0       0.31      0.50      0.38       361
           1       0.30      0.38      0.34       242
           2       0.43      0.25      0.31       310
           3       0.40      0.19      0.25       346
           4       0.26      0.23      0.24       104
           5       0.57      0.23      0.33       239
           6       0.24      0.44      0.31       231

    accuracy                           0.32      1833
   macro avg       0.36      0.32      0.31      1833
weighted avg       0.37      0.32      0.32      1833


Score is appended.

LogisticRegression()

Fitting...
Fitting 5 folds for each of 14 candidates, totallin

model  best_score  \
0                   SVC    0.324604   
1  logistics_regression    0.319694   
2         random_forest    0.277141   

                                         best_params  
0            {'C': 100, 'gamma': 1, 'kernel': 'rbf'}  
1                  {'C': 100, 'solver': 'liblinear'}  
2  {'criterion': 'gini', 'max_depth': None, 'n_es...

# 3. Models after removing repeating characters:

In [15]:
df = pd.read_excel('Code Mixed Hindi-English tweets.xlsx')

### Removing repeating characteres:

In [16]:
tokens = (word_tokenize(i) for i in df.tweets)
df['tweets'] = df['tweets'].apply(nltk.word_tokenize)

pattern = re.compile(r'(.)\1*')

def reduce_sequence_word(word):
    return ''.join([match.group()[:2] if len(match.group()) > 2 else match.group() for match in pattern.finditer(word)])

def reduce_sequence_tweet(tweet):
    return [reduce_sequence_word(word) for word in tweet]

df.tweets = df.tweets.apply(lambda tweet: reduce_sequence_tweet(tweet))
df['tweets'] = df['tweets'].astype(str)

### Splitting data into Train and Test &&& Tokenizing tweets

In [17]:
train, test = train_test_split(df, test_size=0.2, random_state=3)

# Creating a function for tokens
def tokenize_text(text):
    tokens = []
    for sent in nltk.sent_tokenize(text):
        for word in nltk.word_tokenize(sent):
            if len(word) < 2:
                continue
            tokens.append(word.lower())
    return tokens

# Tagging words:
train_tagged = train.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)
test_tagged = test.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)

train_tagged.values[0]

TaggedDocument(words=["'modi", "'ne", "'to", "'ensure", "'kr", "'diya", "'demonetization", "'aur", "'gst", "'unthinkable", "'rates", "'se", "'ki", "'garib", "'marr", "'hi", "'jai", "'ni", "'rha", "'garib", "'aur", "'ni", "'rahegi", "'garibi"], tags=[2])

# Doc2vec:
### Distributed Memory (DM)
Note: If dm=0, distributed bag of words (PV-DBOW) is used; if dm=1,‘distributed memory’ (PV-DM) is used.

### Building DM models:

In [18]:
import multiprocessing
cores = multiprocessing.cpu_count()

model_dmm = Doc2Vec(dm=1, dm_mean=1, vector_size=300, window=10, negative=5, min_count=1, workers=5, alpha=0.065, min_alpha=0.065)
model_dmm.build_vocab([x for x in tqdm(train_tagged.values)])

for epoch in range(30):
    model_dmm.train(shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dmm.alpha -= 0.002
    model_dmm.min_alpha = model_dmm.alpha

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

### Creating Final feature vector:

In [19]:
# Building the Final Feature Vector for the Classifier
def vec_for_learning(model, tagged_docs):
    sents = tagged_docs.values
    targets, regressors = zip(*[(doc.tags[0], model.infer_vector(doc.words)) for doc in sents])
    return targets, regressors

# Creating X_train, X_test, y_train, y_test
y_train, X_train = vec_for_learning(model_dmm, train_tagged)
y_test, X_test = vec_for_learning(model_dmm, test_tagged)

### Results:

In [20]:
%%time

# implemented GridSearchCV for four models using a loop and a previously created dictionary
# in the created variable 'scores', results are stored for each model such as: model, best_score and best_params.

scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, n_jobs=-1, verbose=1) # Using Cross Validation of 5 and n_jobs=-1 for fast training by using all the processors
    print(mp['model'])
    print('\nFitting...')
    best_model = clf.fit(X_train, y_train)                      # Training the model
    clf_pred = best_model.predict(X_test)                       # Predicting the results
    print(confusion_matrix(y_test,clf_pred))                    # Printing Confusion Matrix
    print(metrics.classification_report(y_test, clf_pred))      # Printing Classification Report
    scores.append({                                             # Appending results to 'scores' list
        'model' : model_name,
        'best_score' : best_model.score(X_test, y_test),
        'best_params' : clf.best_params_
    })
    print('\nScore is appended.\n')
    
# Creating data frame with model, best scores and best params:
res = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
res

SVC()

Fitting...
Fitting 5 folds for each of 48 candidates, totalling 240 fits
[[197  45  33  11  15   6  54]
 [ 73  84  17   7   3   6  52]
 [107  46  84  18   8   4  43]
 [112  49  44  43  15   6  77]
 [ 34  10   8   5  25   2  20]
 [ 54  36   9  17  13  69  41]
 [ 61  30   6  11   4   1 118]]
              precision    recall  f1-score   support

           0       0.31      0.55      0.39       361
           1       0.28      0.35      0.31       242
           2       0.42      0.27      0.33       310
           3       0.38      0.12      0.19       346
           4       0.30      0.24      0.27       104
           5       0.73      0.29      0.41       239
           6       0.29      0.51      0.37       231

    accuracy                           0.34      1833
   macro avg       0.39      0.33      0.32      1833
weighted avg       0.39      0.34      0.33      1833


Score is appended.

LogisticRegression()

Fitting...
Fitting 5 folds for each of 14 candidates, totallin

model  best_score  \
0                   SVC    0.338243   
1  logistics_regression    0.346427   
2         random_forest    0.242226   

                                         best_params  
0            {'C': 100, 'gamma': 1, 'kernel': 'rbf'}  
1                  {'C': 100, 'solver': 'liblinear'}  
2  {'criterion': 'gini', 'max_depth': None, 'n_es...

# 4. Models after removing Punctuations:

In [21]:
df = pd.read_excel('Code Mixed Hindi-English tweets.xlsx')

### Removing Punctuations:

In [22]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [23]:
punctuations_list = string.punctuation
def cleaning_punctuations(text):
    translator = str.maketrans('', '', punctuations_list)
    return text.translate(translator)

df['tweets'] = df['tweets'].apply(lambda x: cleaning_punctuations(x))

### Splitting data into Train and Test &&& Tokenizing tweets

In [24]:
train, test = train_test_split(df, test_size=0.2, random_state=3)

# Creating a function for tokens
def tokenize_text(text):
    tokens = []
    for sent in nltk.sent_tokenize(text):
        for word in nltk.word_tokenize(sent):
            if len(word) < 2:
                continue
            tokens.append(word.lower())
    return tokens

# Tagging words:
train_tagged = train.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)
test_tagged = test.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)

train_tagged.values[0]

TaggedDocument(words=['modi', 'ne', 'to', 'ensure', 'kr', 'diya', 'demonetization', 'aur', 'gst', 'unthinkable', 'rates', 'se', 'ki', 'garib', 'marr', 'hi', 'jai', 'ni', 'rha', 'garib', 'aur', 'ni', 'rahegi', 'garibi'], tags=[2])

# Doc2vec:
### Distributed Memory (DM)
Note: If dm=0, distributed bag of words (PV-DBOW) is used; if dm=1,‘distributed memory’ (PV-DM) is used.

### Building DM models:

In [25]:
import multiprocessing
cores = multiprocessing.cpu_count()

model_dmm = Doc2Vec(dm=1, dm_mean=1, vector_size=300, window=10, negative=5, min_count=1, workers=5, alpha=0.065, min_alpha=0.065)
model_dmm.build_vocab([x for x in tqdm(train_tagged.values)])

for epoch in range(30):
    model_dmm.train(shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dmm.alpha -= 0.002
    model_dmm.min_alpha = model_dmm.alpha

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

### Creating Final feature vector:

In [26]:
# Building the Final Feature Vector for the Classifier
def vec_for_learning(model, tagged_docs):
    sents = tagged_docs.values
    targets, regressors = zip(*[(doc.tags[0], model.infer_vector(doc.words)) for doc in sents])
    return targets, regressors

# Creating X_train, X_test, y_train, y_test
y_train, X_train = vec_for_learning(model_dmm, train_tagged)
y_test, X_test = vec_for_learning(model_dmm, test_tagged)

### Results:

In [27]:
%%time

# implemented GridSearchCV for four models using a loop and a previously created dictionary
# in the created variable 'scores', results are stored for each model such as: model, best_score and best_params.

scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, n_jobs=-1, verbose=1) # Using Cross Validation of 5 and n_jobs=-1 for fast training by using all the processors
    print(mp['model'])
    print('\nFitting...')
    best_model = clf.fit(X_train, y_train)                      # Training the model
    clf_pred = best_model.predict(X_test)                       # Predicting the results
    print(confusion_matrix(y_test,clf_pred))                    # Printing Confusion Matrix
    print(metrics.classification_report(y_test, clf_pred))      # Printing Classification Report
    scores.append({                                             # Appending results to 'scores' list
        'model' : model_name,
        'best_score' : best_model.score(X_test, y_test),
        'best_params' : clf.best_params_
    })
    print('\nScore is appended.\n')
    
# Creating data frame with model, best scores and best params:
res = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
res

SVC()

Fitting...
Fitting 5 folds for each of 48 candidates, totalling 240 fits
[[205  37  21  13  21   5  59]
 [ 68  94  19   9  13   5  34]
 [108  47  69   8  18   7  53]
 [110  56  38  32  36  10  64]
 [ 32  12   5   4  33   0  18]
 [ 60  36  12   4  19  61  47]
 [ 66  30   5   5  14   0 111]]
              precision    recall  f1-score   support

           0       0.32      0.57      0.41       361
           1       0.30      0.39      0.34       242
           2       0.41      0.22      0.29       310
           3       0.43      0.09      0.15       346
           4       0.21      0.32      0.26       104
           5       0.69      0.26      0.37       239
           6       0.29      0.48      0.36       231

    accuracy                           0.33      1833
   macro avg       0.38      0.33      0.31      1833
weighted avg       0.39      0.33      0.31      1833


Score is appended.

LogisticRegression()

Fitting...
Fitting 5 folds for each of 14 candidates, totallin

model  best_score  \
0                   SVC    0.330060   
1  logistics_regression    0.340426   
2         random_forest    0.252591   

                                         best_params  
0            {'C': 100, 'gamma': 1, 'kernel': 'rbf'}  
1                  {'C': 100, 'solver': 'liblinear'}  
2  {'criterion': 'entropy', 'max_depth': None, 'n...

# 5. Models after removing numbers:

In [28]:
df = pd.read_excel('Code Mixed Hindi-English tweets.xlsx')

### Removing numbers:

In [29]:
def cleaning_numbers(text):
    return re.sub('[0-9]+', '', text)

df['tweets'] = df['tweets'].apply(lambda text: cleaning_numbers(text))

### Splitting data into Train and Test &&& Tokenizing tweets

In [30]:
train, test = train_test_split(df, test_size=0.2, random_state=3)

# Creating a function for tokens
def tokenize_text(text):
    tokens = []
    for sent in nltk.sent_tokenize(text):
        for word in nltk.word_tokenize(sent):
            if len(word) < 2:
                continue
            tokens.append(word.lower())
    return tokens

# Tagging words:
train_tagged = train.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)
test_tagged = test.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)

train_tagged.values[0]

TaggedDocument(words=['modi', 'ne', 'to', 'ensure', 'kr', 'diya', 'demonetization', 'aur', 'gst', 'unthinkable', 'rates', 'se', 'ki', 'garib', 'marr', 'hi', 'jai', 'ni', 'rha', 'garib', 'aur', 'ni', 'rahegi', 'garibi'], tags=[2])

# Doc2vec:
### Distributed Memory (DM)
Note: If dm=0, distributed bag of words (PV-DBOW) is used; if dm=1,‘distributed memory’ (PV-DM) is used.

### Building DM models:

In [31]:
import multiprocessing
cores = multiprocessing.cpu_count()

model_dmm = Doc2Vec(dm=1, dm_mean=1, vector_size=300, window=10, negative=5, min_count=1, workers=5, alpha=0.065, min_alpha=0.065)
model_dmm.build_vocab([x for x in tqdm(train_tagged.values)])

for epoch in range(30):
    model_dmm.train(shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dmm.alpha -= 0.002
    model_dmm.min_alpha = model_dmm.alpha

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

### Creating Final feature vector:

In [32]:
# Building the Final Feature Vector for the Classifier
def vec_for_learning(model, tagged_docs):
    sents = tagged_docs.values
    targets, regressors = zip(*[(doc.tags[0], model.infer_vector(doc.words)) for doc in sents])
    return targets, regressors

# Creating X_train, X_test, y_train, y_test
y_train, X_train = vec_for_learning(model_dmm, train_tagged)
y_test, X_test = vec_for_learning(model_dmm, test_tagged)

### Results:

In [33]:
%%time

# implemented GridSearchCV for four models using a loop and a previously created dictionary
# in the created variable 'scores', results are stored for each model such as: model, best_score and best_params.

scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, n_jobs=-1, verbose=1) # Using Cross Validation of 5 and n_jobs=-1 for fast training by using all the processors
    print(mp['model'])
    print('\nFitting...')
    best_model = clf.fit(X_train, y_train)                      # Training the model
    clf_pred = best_model.predict(X_test)                       # Predicting the results
    print(confusion_matrix(y_test,clf_pred))                    # Printing Confusion Matrix
    print(metrics.classification_report(y_test, clf_pred))      # Printing Classification Report
    scores.append({                                             # Appending results to 'scores' list
        'model' : model_name,
        'best_score' : best_model.score(X_test, y_test),
        'best_params' : clf.best_params_
    })
    print('\nScore is appended.\n')
    
# Creating data frame with model, best scores and best params:
res = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
res

SVC()

Fitting...
Fitting 5 folds for each of 48 candidates, totalling 240 fits
[[206  33  15  14  22   4  67]
 [ 80  84  11   5  14   4  44]
 [117  44  70  13  18   4  44]
 [129  38  28  37  20  13  81]
 [ 43  12   2   3  30   1  13]
 [ 75  19  19  12  18  63  33]
 [ 60  29   6   2  15   3 116]]
              precision    recall  f1-score   support

           0       0.29      0.57      0.38       361
           1       0.32      0.35      0.34       242
           2       0.46      0.23      0.30       310
           3       0.43      0.11      0.17       346
           4       0.22      0.29      0.25       104
           5       0.68      0.26      0.38       239
           6       0.29      0.50      0.37       231

    accuracy                           0.33      1833
   macro avg       0.39      0.33      0.31      1833
weighted avg       0.40      0.33      0.31      1833


Score is appended.

LogisticRegression()

Fitting...
Fitting 5 folds for each of 14 candidates, totallin

model  best_score  \
0                   SVC    0.330606   
1  logistics_regression    0.327332   
2         random_forest    0.239498   

                                         best_params  
0            {'C': 100, 'gamma': 1, 'kernel': 'rbf'}  
1                  {'C': 100, 'solver': 'liblinear'}  
2  {'criterion': 'entropy', 'max_depth': 20, 'n_e...

# 6. Models after removing all the features:

In [34]:
df = pd.read_excel('Code Mixed Hindi-English tweets.xlsx')

### Removing Punctuations:

In [35]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [36]:
punctuations_list = string.punctuation
def cleaning_punctuations(text):
    translator = str.maketrans('', '', punctuations_list)
    return text.translate(translator)

df['tweets'] = df['tweets'].apply(lambda x: cleaning_punctuations(x))

### Removing Stopwords:

In [37]:
# Using Hinglish stopwords which contains 1036 words from both English and Hindi languages
# Source: https://github.com/TrigonaMinima/HinglishNLP/blob/master/data/assets/stop_hinglish

stopwordlist = ['a', 'aadi', 'aaj', 'aap', 'aapne', 'aata', 'aati', 'aaya', 'aaye', 'ab', 'abbe', 'abbey', 'abe', 'abhi', 'able', 'about', 'above', 'accha', 'according', 'accordingly', 'acha', 'achcha', 'across', 'actually', 'after', 'afterwards', 'again', 'against', 'agar', 'ain', 'aint', "ain't", 'aisa', 'aise', 'aisi', 'alag', 'all', 'allow', 'allows', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'an', 'and', 'andar', 'another', 'any', 'anybody', 'anyhow', 'anyone', 'anything', 'anyway', 'anyways', 'anywhere', 'ap', 'apan', 'apart', 'apna', 'apnaa', 'apne', 'apni', 'appear', 'are', 'aren', 'arent', "aren't", 'around', 'arre', 'as', 'aside', 'ask', 'asking', 'at', 'aur', 'avum', 'aya', 'aye', 'baad', 'baar', 'bad', 'bahut', 'bana', 'banae', 'banai', 'banao', 'banaya', 'banaye', 'banayi', 'banda', 'bande', 'bandi', 'bane', 'bani', 'bas', 'bata', 'batao', 'bc', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'best', 'better', 'between', 'beyond', 'bhai', 'bheetar', 'bhi', 'bhitar', 'bht', 'bilkul', 'bohot', 'bol', 'bola', 'bole', 'boli', 'bolo', 'bolta', 'bolte', 'bolti', 'both', 'brief', 'bro', 'btw', 'but', 'by', 'came', 'can', 'cannot', 'cant', "can't", 'cause', 'causes', 'certain', 'certainly', 'chahiye', 'chaiye', 'chal', 'chalega', 'chhaiye', 'clearly', "c'mon", 'com', 'come', 'comes', 'could', 'couldn', 'couldnt', "couldn't", 'd', 'de', 'dede', 'dega', 'degi', 'dekh', 'dekha', 'dekhe', 'dekhi', 'dekho', 'denge', 'dhang', 'di', 'did', 'didn', 'didnt', "didn't", 'dijiye', 'diya', 'diyaa', 'diye', 'diyo', 'do', 'does', 'doesn', 'doesnt', "doesn't", 'doing', 'done', 'dono', 'dont', "don't", 'doosra', 'doosre', 'down', 'downwards', 'dude', 'dunga', 'dungi', 'during', 'dusra', 'dusre', 'dusri', 'dvaara', 'dvara', 'dwaara', 'dwara', 'each', 'edu', 'eg', 'eight', 'either', 'ek', 'else', 'elsewhere', 'enough', 'etc', 'even', 'ever', 'every', 'everybody', 'everyone', 'everything', 'everywhere', 'ex', 'exactly', 'example', 'except', 'far', 'few', 'fifth', 'fir', 'first', 'five', 'followed', 'following', 'follows', 'for', 'forth', 'four', 'from', 'further', 'furthermore', 'gaya', 'gaye', 'gayi', 'get', 'gets', 'getting', 'ghar', 'given', 'gives', 'go', 'goes', 'going', 'gone', 'good', 'got', 'gotten', 'greetings', 'haan', 'had', 'hadd', 'hadn', 'hadnt', "hadn't", 'hai', 'hain', 'hamara', 'hamare', 'hamari', 'hamne', 'han', 'happens', 'har', 'hardly', 'has', 'hasn', 'hasnt', "hasn't", 'have', 'haven', 'havent', "haven't", 'having', 'he', 'hello', 'help', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', "here's", 'hereupon', 'hers', 'herself', "he's", 'hi', 'him', 'himself', 'his', 'hither', 'hm', 'hmm', 'ho', 'hoga', 'hoge', 'hogi', 'hona', 'honaa', 'hone', 'honge', 'hongi', 'honi', 'hopefully', 'hota', 'hotaa', 'hote', 'hoti', 'how', 'howbeit', 'however', 'hoyenge', 'hoyengi', 'hu', 'hua', 'hue', 'huh', 'hui', 'hum', 'humein', 'humne', 'hun', 'huye', 'huyi', 'i', "i'd", 'idk', 'ie', 'if', "i'll", "i'm", 'imo', 'in', 'inasmuch', 'inc', 'inhe', 'inhi', 'inho', 'inka', 'inkaa', 'inke', 'inki', 'inn', 'inner', 'inse', 'insofar', 'into', 'inward', 'is', 'ise', 'isi', 'iska', 'iskaa', 'iske', 'iski', 'isme', 'isn', 'isne', 'isnt', "isn't", 'iss', 'isse', 'issi', 'isski', 'it', "it'd", "it'll", 'itna', 'itne', 'itni', 'itno', 'its', "it's", 'itself', 'ityaadi', 'ityadi', "i've", 'ja', 'jaa', 'jab', 'jabh', 'jaha', 'jahaan', 'jahan', 'jaisa', 'jaise', 'jaisi', 'jata', 'jayega', 'jidhar', 'jin', 'jinhe', 'jinhi', 'jinho', 'jinhone', 'jinka', 'jinke', 'jinki', 'jinn', 'jis', 'jise', 'jiska', 'jiske', 'jiski', 'jisme', 'jiss', 'jisse', 'jitna', 'jitne', 'jitni', 'jo', 'just', 'jyaada', 'jyada', 'k', 'ka', 'kaafi', 'kab', 'kabhi', 'kafi', 'kaha', 'kahaa', 'kahaan', 'kahan', 'kahi', 'kahin', 'kahte', 'kaisa', 'kaise', 'kaisi', 'kal', 'kam', 'kar', 'kara', 'kare', 'karega', 'karegi', 'karen', 'karenge', 'kari', 'karke', 'karna', 'karne', 'karni', 'karo', 'karta', 'karte', 'karti', 'karu', 'karun', 'karunga', 'karungi', 'kaun', 'kaunsa', 'kayi', 'kch', 'ke', 'keep', 'keeps', 'keh', 'kehte', 'kept', 'khud', 'ki', 'kin', 'kine', 'kinhe', 'kinho', 'kinka', 'kinke', 'kinki', 'kinko', 'kinn', 'kino', 'kis', 'kise', 'kisi', 'kiska', 'kiske', 'kiski', 'kisko', 'kisliye', 'kisne', 'kitna', 'kitne', 'kitni', 'kitno', 'kiya', 'kiye', 'know', 'known', 'knows', 'ko', 'koi', 'kon', 'konsa', 'koyi', 'krna', 'krne', 'kuch', 'kuchch', 'kuchh', 'kul', 'kull', 'kya', 'kyaa', 'kyu', 'kyuki', 'kyun', 'kyunki', 'lagta', 'lagte', 'lagti', 'last', 'lately', 'later', 'le', 'least', 'lekar', 'lekin', 'less', 'lest', 'let', "let's", 'li', 'like', 'liked', 'likely', 'little', 'liya', 'liye', 'll', 'lo', 'log', 'logon', 'lol', 'look', 'looking', 'looks', 'ltd', 'lunga', 'm', 'maan', 'maana', 'maane', 'maani', 'maano', 'magar', 'mai', 'main', 'maine', 'mainly', 'mana', 'mane', 'mani', 'mano', 'many', 'mat', 'may', 'maybe', 'me', 'mean', 'meanwhile', 'mein', 'mera', 'mere', 'merely', 'meri', 'might', 'mightn', 'mightnt', "mightn't", 'mil', 'mjhe', 'more', 'moreover', 'most', 'mostly', 'much', 'mujhe', 'must', 'mustn', 'mustnt', "mustn't", 'my', 'myself', 'na', 'naa', 'naah', 'nahi', 'nahin', 'nai', 'name', 'namely', 'nd', 'ne', 'near', 'nearly', 'necessary', 'neeche', 'need', 'needn', 'neednt', "needn't", 'needs', 'neither', 'never', 'nevertheless', 'new', 'next', 'nhi', 'nine', 'no', 'nobody', 'non', 'none', 'noone', 'nope', 'nor', 'normally', 'not', 'nothing', 'novel', 'now', 'nowhere', 'o', 'obviously', 'of', 'off', 'often', 'oh', 'ok', 'okay', 'old', 'on', 'once', 'one', 'ones', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'ought', 'our', 'ours', 'ourselves', 'out', 'outside', 'over', 'overall', 'own', 'par', 'pata', 'pe', 'pehla', 'pehle', 'pehli', 'people', 'per', 'perhaps', 'phla', 'phle', 'phli', 'placed', 'please', 'plus', 'poora', 'poori', 'provides', 'pura', 'puri', 'q', 'que', 'quite', 'raha', 'rahaa', 'rahe', 'rahi', 'rakh', 'rakha', 'rakhe', 'rakhen', 'rakhi', 'rakho', 'rather', 're', 'really', 'reasonably', 'regarding', 'regardless', 'regards', 'rehte', 'rha', 'rhaa', 'rhe', 'rhi', 'ri', 'right', 's', 'sa', 'saara', 'saare', 'saath', 'sab', 'sabhi', 'sabse', 'sahi', 'said', 'sakta', 'saktaa', 'sakte', 'sakti', 'same', 'sang', 'sara', 'sath', 'saw', 'say', 'saying', 'says', 'se', 'second', 'secondly', 'see', 'seeing', 'seem', 'seemed', 'seeming', 'seems', 'seen', 'self', 'selves', 'sensible', 'sent', 'serious', 'seriously', 'seven', 'several', 'shall', 'shan', 'shant', "shan't", 'she', "she's", 'should', 'shouldn', 'shouldnt', "shouldn't", "should've", 'si', 'since', 'six', 'so', 'soch', 'some', 'somebody', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhat', 'somewhere', 'soon', 'still', 'sub', 'such', 'sup', 'sure', 't', 'tab', 'tabh', 'tak', 'take', 'taken', 'tarah', 'teen', 'teeno', 'teesra', 'teesre', 'teesri', 'tell', 'tends', 'tera', 'tere', 'teri', 'th', 'tha', 'than', 'thank', 'thanks', 'thanx', 'that', "that'll", 'thats', "that's", 'the', 'theek', 'their', 'theirs', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'theres', "there's", 'thereupon', 'these', 'they', "they'd", "they'll", "they're", "they've", 'thi', 'thik', 'thing', 'think', 'thinking', 'third', 'this', 'tho', 'thoda', 'thodi', 'thorough', 'thoroughly', 'those', 'though', 'thought', 'three', 'through', 'throughout', 'thru', 'thus', 'tjhe', 'to', 'together', 'toh', 'too', 'took', 'toward', 'towards', 'tried', 'tries', 'true', 'truly', 'try', 'trying', 'tu', 'tujhe', 'tum', 'tumhara', 'tumhare', 'tumhari', 'tune', 'twice', 'two', 'um', 'umm', 'un', 'under', 'unhe', 'unhi', 'unho', 'unhone', 'unka', 'unkaa', 'unke', 'unki', 'unko', 'unless', 'unlikely', 'unn', 'unse', 'until', 'unto', 'up', 'upar', 'upon', 'us', 'use', 'used', 'useful', 'uses', 'usi', 'using', 'uska', 'uske', 'usne', 'uss', 'usse', 'ussi', 'usually', 'vaala', 'vaale', 'vaali', 'vahaan', 'vahan', 'vahi', 'vahin', 'vaisa', 'vaise', 'vaisi', 'vala', 'vale', 'vali', 'various', 've', 'very', 'via', 'viz', 'vo', 'waala', 'waale', 'waali', 'wagaira', 'wagairah', 'wagerah', 'waha', 'wahaan', 'wahan', 'wahi', 'wahin', 'waisa', 'waise', 'waisi', 'wala', 'wale', 'wali', 'want', 'wants', 'was', 'wasn', 'wasnt', "wasn't", 'way', 'we', "we'd", 'well', "we'll", 'went', 'were', "we're", 'weren', 'werent', "weren't", "we've", 'what', 'whatever', "what's", 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', "where's", 'whereupon', 'wherever', 'whether', 'which', 'while', 'who', 'whoever', 'whole', 'whom', "who's", 'whose', 'why', 'will', 'willing', 'with', 'within', 'without', 'wo', 'woh', 'wohi', 'won', 'wont', "won't", 'would', 'wouldn', 'wouldnt', "wouldn't", 'y', 'ya', 'yadi', 'yah', 'yaha', 'yahaan', 'yahan', 'yahi', 'yahin', 'ye', 'yeah', 'yeh', 'yehi', 'yes', 'yet', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've", 'yup']

STOPWORDS = set(stopwordlist)
def cleaning_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

df['tweets'] = df['tweets'].apply(lambda text: cleaning_stopwords(text))

### Removing Numbers:

In [38]:
def cleaning_numbers(text):
    return re.sub('[0-9]+', '', text)

df['tweets'] = df['tweets'].apply(lambda text: cleaning_numbers(text))

### Removing repeating characters:

In [39]:
tokens = (word_tokenize(i) for i in df.tweets)
df['tweets'] = df['tweets'].apply(nltk.word_tokenize)
#df['tweets'] = df['tweets'].astype(str)

pattern = re.compile(r'(.)\1*')

def reduce_sequence_word(word):
    return ''.join([match.group()[:2] if len(match.group()) > 2 else match.group() for match in pattern.finditer(word)])

def reduce_sequence_tweet(tweet):
    return [reduce_sequence_word(word) for word in tweet]

df.tweets = df.tweets.apply(lambda tweet: reduce_sequence_tweet(tweet))
df['tweets'] = df['tweets'].astype(str)

### Splitting data into Train and Test &&& Tokenizing tweets

In [40]:
train, test = train_test_split(df, test_size=0.2, random_state=3)

# Creating a function for tokens
def tokenize_text(text):
    tokens = []
    for sent in nltk.sent_tokenize(text):
        for word in nltk.word_tokenize(sent):
            if len(word) < 2:
                continue
            tokens.append(word.lower())
    return tokens

# Tagging words:
train_tagged = train.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)
test_tagged = test.apply(
    lambda r: TaggedDocument(words=tokenize_text(r['tweets']), tags=[r.labels]), axis=1)

train_tagged.values[0]

TaggedDocument(words=["'modi", "'ensure", "'kr", "'demonetization", "'gst", "'unthinkable", "'rates", "'garib", "'marr", "'jai", "'ni", "'garib", "'ni", "'rahegi", "'garibi"], tags=[2])

# Doc2vec:
### Distributed Memory (DM)
Note: If dm=0, distributed bag of words (PV-DBOW) is used; if dm=1,‘distributed memory’ (PV-DM) is used.

### Building DM models:

In [41]:
import multiprocessing
cores = multiprocessing.cpu_count()

model_dmm = Doc2Vec(dm=1, dm_mean=1, vector_size=300, window=10, negative=5, min_count=1, workers=5, alpha=0.065, min_alpha=0.065)
model_dmm.build_vocab([x for x in tqdm(train_tagged.values)])

for epoch in range(30):
    model_dmm.train(shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dmm.alpha -= 0.002
    model_dmm.min_alpha = model_dmm.alpha

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

  0%|          | 0/7332 [00:00<?, ?it/s]

### Creating Final feature vector:

In [42]:
# Building the Final Feature Vector for the Classifier
def vec_for_learning(model, tagged_docs):
    sents = tagged_docs.values
    targets, regressors = zip(*[(doc.tags[0], model.infer_vector(doc.words)) for doc in sents])
    return targets, regressors

# Creating X_train, X_test, y_train, y_test
y_train, X_train = vec_for_learning(model_dmm, train_tagged)
y_test, X_test = vec_for_learning(model_dmm, test_tagged)

### Results:

In [43]:
%%time

# implemented GridSearchCV for four models using a loop and a previously created dictionary
# in the created variable 'scores', results are stored for each model such as: model, best_score and best_params.

scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, n_jobs=-1, verbose=1) # Using Cross Validation of 5 and n_jobs=-1 for fast training by using all the processors
    print(mp['model'])
    print('\nFitting...')
    best_model = clf.fit(X_train, y_train)                      # Training the model
    clf_pred = best_model.predict(X_test)                       # Predicting the results
    print(confusion_matrix(y_test,clf_pred))                    # Printing Confusion Matrix
    print(metrics.classification_report(y_test, clf_pred))      # Printing Classification Report
    scores.append({                                             # Appending results to 'scores' list
        'model' : model_name,
        'best_score' : best_model.score(X_test, y_test),
        'best_params' : clf.best_params_
    })
    print('\nScore is appended.\n')
    
# Creating data frame with model, best scores and best params:
res = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
res

SVC()

Fitting...
Fitting 5 folds for each of 48 candidates, totalling 240 fits
[[195  37  34  15  10  12  58]
 [ 70  84  19   5   3   6  55]
 [ 98  46  69  20  12  12  53]
 [ 92  55  28  60   7  17  87]
 [ 25  13   8   7  24   4  23]
 [ 57  23  18  18   6  52  65]
 [ 82  17  13  10   3   4 102]]
              precision    recall  f1-score   support

           0       0.32      0.54      0.40       361
           1       0.31      0.35      0.32       242
           2       0.37      0.22      0.28       310
           3       0.44      0.17      0.25       346
           4       0.37      0.23      0.28       104
           5       0.49      0.22      0.30       239
           6       0.23      0.44      0.30       231

    accuracy                           0.32      1833
   macro avg       0.36      0.31      0.31      1833
weighted avg       0.36      0.32      0.31      1833


Score is appended.

LogisticRegression()

Fitting...
Fitting 5 folds for each of 14 candidates, totallin

model  best_score  \
0                   SVC    0.319694   
1  logistics_regression    0.330606   
2         random_forest    0.295145   

                                         best_params  
0            {'C': 100, 'gamma': 1, 'kernel': 'rbf'}  
1                  {'C': 100, 'solver': 'liblinear'}  
2  {'criterion': 'gini', 'max_depth': 20, 'n_esti...